/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jshaz_daigo_util_SecurityJni */

#ifndef _Included_com_jshaz_daigo_util_SecurityJni
#define _Included_com_jshaz_daigo_util_SecurityJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jshaz_daigo_util_SecurityJni
 * Method:    getSL
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jshaz_daigo_util_SecurityJni_getSL
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
